version: "3.9"
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev
