import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ポートフォリオ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.inner}>
        <section className={styles.section}>
          <div>
            <h1 className={styles.title}>
              Engineer<br />
              s.yasunaga
            </h1>
            <h2 className={styles.sub}>
              エンジニアリングで世の中を<br />
              もっと便利で楽しい世界へ
            </h2>
          </div>
          <Image
            className={styles.image}
            src="/image.jpeg"
            alt="image"
            width={230}
            height={230}
          />
        </section>
        <section className={styles.introduction}>
          <div className={styles.box}></div>
          <h2 className={styles.sub}>自己紹介</h2>
          <p className={styles.text}>
            はじめまして！
            東京でエンジニアをしています、安永（やすなが）と申します。<br />
            2013年頃、大学時代にプログラミング（Java）に出会い、独学でプログラムを書き、その楽しさに目覚めました。<br />
            2017年4月から、SIerの企業に新卒で入社をし、それから現在に至るまでフルスタックエンジニアとして
            さまざまな企業でエンジニアリングをリードしてきました。
            得意なのは、バックエンドのコーディング・インフラ構築・データベース設計などです。<br />
            好きなことは、麻雀・ギター・ビリヤード・お酒などなどです。
          </p>
        </section>
      </div>
    </div>
  )
}
